package com.account.app.commons;

public interface DBQueries {
	String SELECT_ALL_ACCNT = "SELECT ID, NAME, DESCRIPTION, CREATEDATE, CREATEDUSER, LASTMODIFIED, UPDATEDUSER FROM ACCOUNT";
	String SELECT_ACCNT_BY_ID = "SELECT ID, NAME, DESCRIPTION, CREATEDATE, CREATEDUSER, LASTMODIFIED, UPDATEDUSER FROM ACCOUNT WHERE ID=:id";
	String INSERT_ACCNT_ORA = "INSERT INTO ACCOUNT ( ID, NAME, DESCRIPTION, CREATEDATE, CREATEDUSER, LASTMODIFIED, UPDATEDUSER ) VALUES ( ACCNT_ID.nextval, :name, :description, :createdate, :createduser, :lastmodified, :updateduser )";
	String INSERT_ACCNT = "INSERT INTO ACCOUNT ( NAME, DESCRIPTION, CREATEDATE, CREATEDUSER, LASTMODIFIED, UPDATEDUSER ) VALUES ( :name, :description, :createdate, :createduser, :lastmodified, :updateduser )";
	String UPDTE_ACCNT_BY_ID = "UPDATE ACCOUNT SET name = :name, description = :description,  lastmodified = :lastmodified, UPDATEDUSER = :updateduser WHERE id = :id";
	String DELTE_ACCNT_BY_ID = "DELETE FROM ACCOUNT WHERE ID = :id";
	String GET_ACCNT_WITH_MAX_ID="SELECT ID, NAME, DESCRIPTION, CREATEDATE, CREATEDUSER, LASTMODIFIED, UPDATEDUSER FROM ACCOUNT WHERE ID=(SELECT MAX(ID) FROM ACCOUNT )";
}
