CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
DESCRIPTION VARCHAR(50),
STATUS VARCHAR(10),
CREATEDATE TIMESTAMP,
CREATEDUSER VARCHAR(20),
LASTMODIFIED TIMESTAMP,
UPDATEDUSER VARCHAR(20) 
);

ALTER TABLE ACCOUNT ALTER NAME SET NOT NULL;
ALTER TABLE ACCOUNT ALTER STATUS SET NOT NULL;
ALTER TABLE ACCOUNT ALTER CREATEDATE SET NOT NULL;
ALTER TABLE ACCOUNT ALTER CREATEDUSER SET NOT NULL;
ALTER TABLE ACCOUNT ALTER LASTMODIFIED SET NOT NULL;
ALTER TABLE ACCOUNT ALTER UPDATEDUSER SET NOT NULL;
